### ISSUE TITLE
resend data for Langford, Anderson?

### ISSUE THREAD

**Issue by jbrzusto** [StuMackenzie/TODO#4]
Data for these sites ends on:

```
  Langford:   2016-08-12
  Anderson:   2016-08-25
```

An expired wetransfer suggests there might be a few more days for each site.  If so, best to send
starting with date shown above.

**Comment by StuMackenzie** [comment]
Zoe - I think you already took care of this, if so, can you close the issue. Thanks.

**Comment by zcrysler** [comment]
The files were sent and downloaded by the automatic email, but haven't been updated on sensorgnome yet. They should both have data up to september 9
